#! /bin/bash
# Shell script to compress pdf using ghostscript lib.
##### Functions
usage() {
    echo -e "\033[1mHelp\033[0m \n
        compresspdf [-f [file] -s [\033[1mscreen\033[0m|ebook|printer|prepress|default] -i [initial page] -e [end page] -g | -h ] \n
    \033[1m**\033[0m Default conversion setting is screen. Use initial and end numbers for splitting pages. \n
Then: \n
- You get the output \033[1mfilename_small.pdf\033[0m \n"
}
compresspdf() {
    gs -sDEVICE=pdfwrite -dNOPAUSE -dQUIET -dBATCH -dPDFSETTINGS=/${setting:-"screen"} -dCompatibilityLevel=1.4 ${additionals:-} -sOutputFile="$DST" "$SRC" 2>&1 > /dev/null
}
##### Main
for arg in "$@"; do
  shift
  case "$arg" in
    "--help")       set -- "$@" "-h" ;;
    "--file")       set -- "$@" "-f" ;;
    "--setting")    set -- "$@" "-s" ;;
    "--initial")    set -- "$@" "-i" ;;
    "--end")        set -- "$@" "-e" ;;
    "--gray")       set -- "$@" "-g" ;;
    "--?")          set -- "$@" "-?" ;;
    *)              set -- "$@" "$arg"
  esac
done
OPTIND=1
while getopts ":h:f:s:i:e:g?" opt; do
  case "$opt" in
    "h")    usage
            exit 0
            ;;
    "f")    SRC=$OPTARG
            DST="${SRC%.*}"_small.pdf
            ;;
    "s")    setting=$OPTARG
            ;;
    "i")    initial=$OPTARG
            ;;
    "e")    end=$OPTARG
            ;;
    "g")    gray=true
            ;;
    "?")    usage
            exit 1
            ;;
    *)      usage
            exit 1
  esac
done
shift $(expr $OPTIND - 1)
if [[ ! $SRC ]]; then
    echo -e "\033[1mWarning\033[0m \n
    At least an input file is required to convert! \n
        Use \033[1mcompresspdf -h\033[0m for help. \n"
    exit 1
else
    if [[ -f $SRC ]]; then
        if [[ $initial || $end ]]; then
            if [[ $initial && $end ]]; then
                splitopt=" -dFirstPage=$initial -dLastPage=$end"
                if [[ ! $additionals ]]; then
                    additionals=$splitopt
                else
                    additionals=$additionals$splitopt
                fi
            else
                echo -e "\033[1mWarning\033[0m \n
                For split options it´s neccesary both, the [-i (--initial)] and [-e (--end)] pages  to continue! \n
                    Use \033[1mcompresspdf -h\033[0m for help. \n"
                exit 1
            fi
        fi
        if [[ $gray ]]; then
            grayopt=" -sProcessColorModel=DeviceGray -sColorConversionStrategy=Gray -dOverrideICC"
            if [[ ! $additionals ]]; then
                additionals=$grayopt
            else
                additionals=$additionals$grayopt
            fi
        fi
        compresspdf > /dev/null
        if [ $? -eq 0 ]; then
            echo -e "\033[1mInfo\033[0m \n
        The output file was saved to $DST \n"
            exit 0
        else
            echo -e "\033[1mError\033[0m \n
        \033[1mProblem\033[0m occur with conversion, please try again!! \n"
            exit 1
        fi
    else
        echo -e "\033[1mError\033[0m \n
    File \033[1m$SRC\033[0m to convert not found! \n"
        exit 1
    fi
fi
